//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Views.BaoCao {
    
    
    public partial class BaoCaoThongKe {
        
        /// <summary>
        /// lblReportType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblReportType;
        
        /// <summary>
        /// listReportVNP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportVNP;
        
        /// <summary>
        /// lbReport_VNP_BaoCaoTongHopGiamTruTheoCP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_BaoCaoTongHopGiamTruTheoCP;
        
        /// <summary>
        /// lbReport_VNP_DoiSoatCSKHPTDV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_DoiSoatCSKHPTDV;
        
        /// <summary>
        /// lbReport_VNP_DanhSachQuaHan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_DanhSachQuaHan;
        
        /// <summary>
        /// lbReport_VNP_KhieuNaiToanMang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_KhieuNaiToanMang;
        
        /// <summary>
        /// lbReport_VNP_KhieuNaiToanMangTheoTuan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_KhieuNaiToanMangTheoTuan;
        
        /// <summary>
        /// lbReport_VNP_KhieuNaiToanMangTheoThang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_KhieuNaiToanMangTheoThang;
        
        /// <summary>
        /// lbReport_VNP_ThongKeKhieuNaiTheoNguyenNhanLoi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_ThongKeKhieuNaiTheoNguyenNhanLoi;
        
        /// <summary>
        /// lbReport_VNP_BaoCaoChatLuongPhucVu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_BaoCaoChatLuongPhucVu;
        
        /// <summary>
        /// lbReport_VNP_BaoCaoChatLuongMang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_BaoCaoChatLuongMang;
        
        /// <summary>
        /// lbReport_VNP_BaoCaoTonDongQuaHan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_BaoCaoTonDongQuaHan;
        
        /// <summary>
        /// lbReport_VNP_BaoCaoDVGTGTTapDoan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_BaoCaoDVGTGTTapDoan;
        
        /// <summary>
        /// lbReport_VNP_BaoCaoTongHopGiamTruVNPTTT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_BaoCaoTongHopGiamTruVNPTTT;
        
        /// <summary>
        /// lbReport_VNP_BaoCaoTongHopGiamTru control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_BaoCaoTongHopGiamTru;
        
        /// <summary>
        /// lbReport_VNP_DanhSachGiamTruKhieuNai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_DanhSachGiamTruKhieuNai;
        
        /// <summary>
        /// lbReport_VNP_BaoCaoTongHopToGQKN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_BaoCaoTongHopToGQKN;
        
        /// <summary>
        /// lbReport_VNP_BaoCaoGiamTruToGQKN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_BaoCaoGiamTruToGQKN;
        
        /// <summary>
        /// listReportGiamTruDVGTGT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportGiamTruDVGTGT;
        
        /// <summary>
        /// LinkButton7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton7;
        
        /// <summary>
        /// LinkButton8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton8;
        
        /// <summary>
        /// lbReport_VNP_BaoCaoChiTietGiamTruDVGTGT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_BaoCaoChiTietGiamTruDVGTGT;
        
        /// <summary>
        /// lbReport_VNP_BaoCaoTongHopTheoChiTieuThoiGianGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_BaoCaoTongHopTheoChiTieuThoiGianGiaiQuyet;
        
        /// <summary>
        /// lbReport_VNP_BaoCaoChiTietTheoChiTieuThoiGianGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNP_BaoCaoChiTietTheoChiTieuThoiGianGiaiQuyet;
        
        /// <summary>
        /// listReportGQKN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportGQKN;
        
        /// <summary>
        /// lblReport_GQKN_BaoCaoTongHopLoaiKhieuNai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lblReport_GQKN_BaoCaoTongHopLoaiKhieuNai;
        
        /// <summary>
        /// lbReport11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport11;
        
        /// <summary>
        /// lbReport81 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport81;
        
        /// <summary>
        /// lbReport_GQKN_ChiTietGiamTruTraSauVNPTTT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_GQKN_ChiTietGiamTruTraSauVNPTTT;
        
        /// <summary>
        /// lbReport21 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport21;
        
        /// <summary>
        /// lbReport41 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport41;
        
        /// <summary>
        /// lbReport51 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport51;
        
        /// <summary>
        /// lbReport61 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport61;
        
        /// <summary>
        /// lbReportBieuDo_TheoLinhVucCon_GQKN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportBieuDo_TheoLinhVucCon_GQKN;
        
        /// <summary>
        /// lbReport_GQKN_BaoCaoKhieuNaiChuyenBoPhanKhac control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_GQKN_BaoCaoKhieuNaiChuyenBoPhanKhac;
        
        /// <summary>
        /// lbReport_GQKN_PhongBanCaNhan_TongHopPhongBan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_GQKN_PhongBanCaNhan_TongHopPhongBan;
        
        /// <summary>
        /// lbReport_GQKN_PhongBanCaNhan_TongHopNguoiDung control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_GQKN_PhongBanCaNhan_TongHopNguoiDung;
        
        /// <summary>
        /// lblReport_GQKN_CSKHKV_GiamTruKhieuNaiDichVu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lblReport_GQKN_CSKHKV_GiamTruKhieuNaiDichVu;
        
        /// <summary>
        /// lblReport_GQKN_CSKHKV_KhieuNaiDichVu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lblReport_GQKN_CSKHKV_KhieuNaiDichVu;
        
        /// <summary>
        /// lblReport_GQKN_CSKHKV_ThucTrangGQKN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lblReport_GQKN_CSKHKV_ThucTrangGQKN;
        
        /// <summary>
        /// lblReport_GQKN_CSKHKV_BaoCaoTongHopGiamTruCuocDVGTGTTheoCP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lblReport_GQKN_CSKHKV_BaoCaoTongHopGiamTruCuocDVGTGTTheoCP;
        
        /// <summary>
        /// lblReport_GQKN_CSKHKV_BaoCaoTongHop control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lblReport_GQKN_CSKHKV_BaoCaoTongHop;
        
        /// <summary>
        /// lblReport_GQKN_CSKHKV_BaoCaoTongHopGiamTruVNPTTT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lblReport_GQKN_CSKHKV_BaoCaoTongHopGiamTruVNPTTT;
        
        /// <summary>
        /// listReportXLNV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportXLNV;
        
        /// <summary>
        /// lbReport31 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport31;
        
        /// <summary>
        /// lbReport_XLNV_BaoCaoKhoiLuongCongViec control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_XLNV_BaoCaoKhoiLuongCongViec;
        
        /// <summary>
        /// lbReportBieuDo_TheoLinhVucCon_XLNV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportBieuDo_TheoLinhVucCon_XLNV;
        
        /// <summary>
        /// lbReport_XLNV_BaoCaoTonDongQuaHanCuaDoiTac control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_XLNV_BaoCaoTonDongQuaHanCuaDoiTac;
        
        /// <summary>
        /// lbReport_XLNV_BaoCaoKhieuNaiChuyenBoPhanKhac control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_XLNV_BaoCaoKhieuNaiChuyenBoPhanKhac;
        
        /// <summary>
        /// lbReport_XLNV_PhongBanCaNhan_TongHopPhongBan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_XLNV_PhongBanCaNhan_TongHopPhongBan;
        
        /// <summary>
        /// lbReport_XLNV_PhongBanCaNhan_TongHopNguoiDung control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_XLNV_PhongBanCaNhan_TongHopNguoiDung;
        
        /// <summary>
        /// lbReport_XLNV_ThongKeKhieuNaiTheoNguyenNhanLoi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_XLNV_ThongKeKhieuNaiTheoNguyenNhanLoi;
        
        /// <summary>
        /// lbReport_XLNV_DanhSachQuaHan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_XLNV_DanhSachQuaHan;
        
        /// <summary>
        /// listReportKS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportKS;
        
        /// <summary>
        /// lbReport_KS_BaoCaoTongHopKN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_KS_BaoCaoTongHopKN;
        
        /// <summary>
        /// lbReportBieuDo_TheoLinhVucCon_KS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportBieuDo_TheoLinhVucCon_KS;
        
        /// <summary>
        /// lbReport_KS_PhongBanCaNhan_TongHopPhongBan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_KS_PhongBanCaNhan_TongHopPhongBan;
        
        /// <summary>
        /// lbReport_KS_PhongBanCaNhan_TongHopNguoiDung control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_KS_PhongBanCaNhan_TongHopNguoiDung;
        
        /// <summary>
        /// listReportOB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportOB;
        
        /// <summary>
        /// lbReport_OB_BaoCaoTongHopKN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_OB_BaoCaoTongHopKN;
        
        /// <summary>
        /// lbReportBieuDo_TheoLinhVucCon_OB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportBieuDo_TheoLinhVucCon_OB;
        
        /// <summary>
        /// lbReport_OB_PhongBanCaNhan_TongHopPhongBan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_OB_PhongBanCaNhan_TongHopPhongBan;
        
        /// <summary>
        /// lbReport_OB_PhongBanCaNhan_TongHopNguoiDung control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_OB_PhongBanCaNhan_TongHopNguoiDung;
        
        /// <summary>
        /// listReportKTV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportKTV;
        
        /// <summary>
        /// lbReport_TTKTV_BaoCaoSoLuongKNPhanHoiVeKTV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_TTKTV_BaoCaoSoLuongKNPhanHoiVeKTV;
        
        /// <summary>
        /// lbReport_TTKTV_BaoCaoSoLuongKNQuaHanCuaKTV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_TTKTV_BaoCaoSoLuongKNQuaHanCuaKTV;
        
        /// <summary>
        /// lbReportBieuDo_TheoLinhVucCon_KTV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportBieuDo_TheoLinhVucCon_KTV;
        
        /// <summary>
        /// listReportTTTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportTTTC;
        
        /// <summary>
        /// lbReportTTTC_TongHopPAKN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportTTTC_TongHopPAKN;
        
        /// <summary>
        /// lbReportTTTC_TongHopPAKNTheoPhongBan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportTTTC_TongHopPAKNTheoPhongBan;
        
        /// <summary>
        /// lbReportTTTC_TongHopPAKNTheoNguoiDung control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportTTTC_TongHopPAKNTheoNguoiDung;
        
        /// <summary>
        /// lbReportTTTC_ChiTietPAKNTheoNguoiDung control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportTTTC_ChiTietPAKNTheoNguoiDung;
        
        /// <summary>
        /// lbReportTTTC_BaoCaoPhoiHopGQKN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportTTTC_BaoCaoPhoiHopGQKN;
        
        /// <summary>
        /// lbReportTTTC_BaoCaoQuaHanPhongBan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportTTTC_BaoCaoQuaHanPhongBan;
        
        /// <summary>
        /// lbReportTTTC_DanhSachQuaHan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportTTTC_DanhSachQuaHan;
        
        /// <summary>
        /// lbReportTTTC_BaoCaoTongHopGiamTru control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportTTTC_BaoCaoTongHopGiamTru;
        
        /// <summary>
        /// lbReportTTTC_VNP_KhieuNaiToanMang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportTTTC_VNP_KhieuNaiToanMang;
        
        /// <summary>
        /// lbReportTTTC_VNP_ThongKeKhieuNaiTheoNguyenNhanLoi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportTTTC_VNP_ThongKeKhieuNaiTheoNguyenNhanLoi;
        
        /// <summary>
        /// lbReportTTTC_VNP_BaoCaoChatLuongMang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportTTTC_VNP_BaoCaoChatLuongMang;
        
        /// <summary>
        /// listReportVAS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportVAS;
        
        /// <summary>
        /// lbReport_SoLieuPAKNDichVuToanMang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_SoLieuPAKNDichVuToanMang;
        
        /// <summary>
        /// lbReport_VAS_TongHopPAKN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VAS_TongHopPAKN;
        
        /// <summary>
        /// lbReport_VAS_TongHopPAKNTheoNguoiDung control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VAS_TongHopPAKNTheoNguoiDung;
        
        /// <summary>
        /// lbReport_SoLieuPAKNDaXuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_SoLieuPAKNDaXuLy;
        
        /// <summary>
        /// lbReport_TongHopSoLieuPAKNDangTonDong control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_TongHopSoLieuPAKNDangTonDong;
        
        /// <summary>
        /// lbReport_TongHopSoLieuPAKNDaTiepNhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_TongHopSoLieuPAKNDaTiepNhan;
        
        /// <summary>
        /// lbReport_ChiTietPAKNDaTiepNhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_ChiTietPAKNDaTiepNhan;
        
        /// <summary>
        /// lbReportVAS_BaoCaoTongDonNguoiDungPhongBan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportVAS_BaoCaoTongDonNguoiDungPhongBan;
        
        /// <summary>
        /// lbReportVAS_DanhSachQuaHan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportVAS_DanhSachQuaHan;
        
        /// <summary>
        /// lbReportVAS_BaoCaoTongHopGiamTru control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportVAS_BaoCaoTongHopGiamTru;
        
        /// <summary>
        /// listReportCSKHKhuVuc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportCSKHKhuVuc;
        
        /// <summary>
        /// lbReport_CSKHKV_GiamTruKhieuNaiDichVu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_CSKHKV_GiamTruKhieuNaiDichVu;
        
        /// <summary>
        /// lbReport_CSKHKV_KhieuNaiDichVu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_CSKHKV_KhieuNaiDichVu;
        
        /// <summary>
        /// lbReport_CSKHKV_ThucTrangGQKN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_CSKHKV_ThucTrangGQKN;
        
        /// <summary>
        /// lbReport_CSKHKV_BaoCaoTongHopGiamTruCuocDVGTGTTheoCP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_CSKHKV_BaoCaoTongHopGiamTruCuocDVGTGTTheoCP;
        
        /// <summary>
        /// lbReport_CSKHKV_BaoCaoTongHop control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_CSKHKV_BaoCaoTongHop;
        
        /// <summary>
        /// lbReport_CSKHKV_BaoCaoTongHopGiamTruVNPTTT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_CSKHKV_BaoCaoTongHopGiamTruVNPTTT;
        
        /// <summary>
        /// lbReport_CSKHKV_DanhSachKhieuNaiQuaHan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_CSKHKV_DanhSachKhieuNaiQuaHan;
        
        /// <summary>
        /// lbReport_CSKHKV_BaoCaoTongHopTaiPhongBan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_CSKHKV_BaoCaoTongHopTaiPhongBan;
        
        /// <summary>
        /// lbReport_CSKHKV_BaoCaoTongHopNguoiDungTaiPhongBan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_CSKHKV_BaoCaoTongHopNguoiDungTaiPhongBan;
        
        /// <summary>
        /// listReportVNPTTT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportVNPTTT;
        
        /// <summary>
        /// lbReport_VNPTTT_GiamTruKhieuNaiDichVu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNPTTT_GiamTruKhieuNaiDichVu;
        
        /// <summary>
        /// lbReport_VNPTTT_KhieuNaiDichVu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNPTTT_KhieuNaiDichVu;
        
        /// <summary>
        /// lbReport_VNPTTT_ThucTrangGQKN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNPTTT_ThucTrangGQKN;
        
        /// <summary>
        /// lbReport_VNPTTT_BaoCaoTongHopGiamTruCuocDVGTGTTheoCP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNPTTT_BaoCaoTongHopGiamTruCuocDVGTGTTheoCP;
        
        /// <summary>
        /// lbReport_VNPTTT_TongHopPAKNTVTT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNPTTT_TongHopPAKNTVTT;
        
        /// <summary>
        /// lbReport_VNPTTT_TongHopPAKNPhongBanVTT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNPTTT_TongHopPAKNPhongBanVTT;
        
        /// <summary>
        /// lbReport_VNPTTT_TongHopPAKNTheoNguoiDung control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNPTTT_TongHopPAKNTheoNguoiDung;
        
        /// <summary>
        /// lbReport_VNPTTT_TongHopPAKNTheoThang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNPTTT_TongHopPAKNTheoThang;
        
        /// <summary>
        /// listReportTruongDaiDien control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportTruongDaiDien;
        
        /// <summary>
        /// lbReport_TDD_GiamTruKhieuNaiDichVu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_TDD_GiamTruKhieuNaiDichVu;
        
        /// <summary>
        /// lbReport_TDD_KhieuNaiDichVu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_TDD_KhieuNaiDichVu;
        
        /// <summary>
        /// lbReport_TDD_ThucTrangGQKN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_TDD_ThucTrangGQKN;
        
        /// <summary>
        /// lbReport_TDD_BaoCaoTongHopGiamTruCuocDVGTGTTheoCP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_TDD_BaoCaoTongHopGiamTruCuocDVGTGTTheoCP;
        
        /// <summary>
        /// listReportDoiTac control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportDoiTac;
        
        /// <summary>
        /// lbReport_DoiTac_BaoCaoSoLuongChuyenXuLyVNP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_DoiTac_BaoCaoSoLuongChuyenXuLyVNP;
        
        /// <summary>
        /// lbReport_DoiTac_TongHopDonVi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_DoiTac_TongHopDonVi;
        
        /// <summary>
        /// lbReport_DoiTac_TongHopPhongBan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_DoiTac_TongHopPhongBan;
        
        /// <summary>
        /// lbReport_DoiTac_TongHopNguoiDung control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_DoiTac_TongHopNguoiDung;
        
        /// <summary>
        /// listReportVNPTNET control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportVNPTNET;
        
        /// <summary>
        /// lbReport_VNPTNET_BaoCaoChatLuongMang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNPTNET_BaoCaoChatLuongMang;
        
        /// <summary>
        /// lbReport_VNPTNET_BaoCaoTongHopVNPTNET control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNPTNET_BaoCaoTongHopVNPTNET;
        
        /// <summary>
        /// lbReport_VNPTNET_BaoCaoTongHopDonVi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNPTNET_BaoCaoTongHopDonVi;
        
        /// <summary>
        /// lbReport_VNPTNET_BaoCaoTongHopPhongBan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNPTNET_BaoCaoTongHopPhongBan;
        
        /// <summary>
        /// lbReport_VNPTNET_BaoCaoTongHopNguoiDung control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_VNPTNET_BaoCaoTongHopNguoiDung;
        
        /// <summary>
        /// listReportHaTangMang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportHaTangMang;
        
        /// <summary>
        /// lbReportHTM_VNP_BaoCaoChatLuongMang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportHTM_VNP_BaoCaoChatLuongMang;
        
        /// <summary>
        /// LinkButton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton1;
        
        /// <summary>
        /// LinkButton2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton2;
        
        /// <summary>
        /// LinkButton3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton3;
        
        /// <summary>
        /// listReportDHTT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportDHTT;
        
        /// <summary>
        /// lbReportDHTT_VNP_BaoCaoChatLuongMang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReportDHTT_VNP_BaoCaoChatLuongMang;
        
        /// <summary>
        /// LinkButton4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton4;
        
        /// <summary>
        /// LinkButton5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton5;
        
        /// <summary>
        /// LinkButton6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton6;
        
        /// <summary>
        /// listReportNETCNTT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportNETCNTT;
        
        /// <summary>
        /// LinkButton9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton9;
        
        /// <summary>
        /// LinkButton10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton10;
        
        /// <summary>
        /// listReportCaNhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl listReportCaNhan;
        
        /// <summary>
        /// lbReport_CaNhan_TongHopCaNhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbReport_CaNhan_TongHopCaNhan;
        
        /// <summary>
        /// pnContainer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnContainer;
    }
}
