//------------------------------------------------------------------------------
                                        // <auto-generated>
                                        //     This code was generated by a tool.
                                        //     Runtime Version:2.0.50727.4927
                                        //
                                        //     Changes to this file may cause incorrect behavior and will be lost if
                                        //     the code is regenerated.
                                        // </auto-generated>
                                        //------------------------------------------------------------------------------
public partial class admin_khieuNai_FileDinhKem_add {
/// <summary>
                                        /// lblMsg control.
                                        /// </summary>
                                        /// <remarks>
                                        /// Auto-generated field.
                                        /// To modify move field declaration from designer file to code-behind file.
                                        /// </remarks>
                                        protected global::System.Web.UI.WebControls.Label lblMsg;
    
                                        /// <summary>
                                        /// btSubmit control.
                                        /// </summary>
                                        /// <remarks>
                                        /// Auto-generated field.
                                        /// To modify move field declaration from designer file to code-behind file.
                                        /// </remarks>
                                        protected global::System.Web.UI.WebControls.Button btSubmit;

/// <summary>
                                                /// ddlKhieuNaiId control.
                                                /// </summary>
                                                /// <remarks>
                                                /// Auto-generated field.
                                                /// To modify move field declaration from designer file to code-behind file.
                                                /// </remarks>
                                                protected global::System.Web.UI.WebControls.DropDownList ddlKhieuNaiId;

/// <summary>
                                                /// txtTenFile control.
                                                /// </summary>
                                                /// <remarks>
                                                /// Auto-generated field.
                                                /// To modify move field declaration from designer file to code-behind file.
                                                /// </remarks>
                                                protected global::System.Web.UI.WebControls.TextBox txtTenFile;

/// <summary>
                                                /// txtKichThuoc control.
                                                /// </summary>
                                                /// <remarks>
                                                /// Auto-generated field.
                                                /// To modify move field declaration from designer file to code-behind file.
                                                /// </remarks>
                                                protected global::System.Web.UI.WebControls.TextBox txtKichThuoc;

/// <summary>
                                                /// txtLoaiFile control.
                                                /// </summary>
                                                /// <remarks>
                                                /// Auto-generated field.
                                                /// To modify move field declaration from designer file to code-behind file.
                                                /// </remarks>
                                                protected global::System.Web.UI.WebControls.TextBox txtLoaiFile;

/// <summary>
                                                /// txtGhiChu control.
                                                /// </summary>
                                                /// <remarks>
                                                /// Auto-generated field.
                                                /// To modify move field declaration from designer file to code-behind file.
                                                /// </remarks>
                                                protected global::System.Web.UI.WebControls.TextBox txtGhiChu;

/// <summary>
                                                /// txtURLFile control.
                                                /// </summary>
                                                /// <remarks>
                                                /// Auto-generated field.
                                                /// To modify move field declaration from designer file to code-behind file.
                                                /// </remarks>
                                                protected global::System.Web.UI.WebControls.TextBox txtURLFile;
}


