//------------------------------------------------------------------------------
                                        // <auto-generated>
                                        //     This code was generated by a tool.
                                        //     Runtime Version:2.0.50727.4927
                                        //
                                        //     Changes to this file may cause incorrect behavior and will be lost if
                                        //     the code is regenerated.
                                        // </auto-generated>
                                        //------------------------------------------------------------------------------
public partial class admin_khieuNai_Log_add {
/// <summary>
                                        /// lblMsg control.
                                        /// </summary>
                                        /// <remarks>
                                        /// Auto-generated field.
                                        /// To modify move field declaration from designer file to code-behind file.
                                        /// </remarks>
                                        protected global::System.Web.UI.WebControls.Label lblMsg;
    
                                        /// <summary>
                                        /// btSubmit control.
                                        /// </summary>
                                        /// <remarks>
                                        /// Auto-generated field.
                                        /// To modify move field declaration from designer file to code-behind file.
                                        /// </remarks>
                                        protected global::System.Web.UI.WebControls.Button btSubmit;

/// <summary>
                                                /// txtKhieuNaiId control.
                                                /// </summary>
                                                /// <remarks>
                                                /// Auto-generated field.
                                                /// To modify move field declaration from designer file to code-behind file.
                                                /// </remarks>
                                                protected global::System.Web.UI.WebControls.TextBox txtKhieuNaiId;

/// <summary>
                                                /// txtTruongThayDoi control.
                                                /// </summary>
                                                /// <remarks>
                                                /// Auto-generated field.
                                                /// To modify move field declaration from designer file to code-behind file.
                                                /// </remarks>
                                                protected global::System.Web.UI.WebControls.TextBox txtTruongThayDoi;

/// <summary>
                                                /// txtGiaTriCu control.
                                                /// </summary>
                                                /// <remarks>
                                                /// Auto-generated field.
                                                /// To modify move field declaration from designer file to code-behind file.
                                                /// </remarks>
                                                protected global::System.Web.UI.WebControls.TextBox txtGiaTriCu;

/// <summary>
                                                /// txtGiaTriMoi control.
                                                /// </summary>
                                                /// <remarks>
                                                /// Auto-generated field.
                                                /// To modify move field declaration from designer file to code-behind file.
                                                /// </remarks>
                                                protected global::System.Web.UI.WebControls.TextBox txtGiaTriMoi;

/// <summary>
                                                /// txtThaoTac control.
                                                /// </summary>
                                                /// <remarks>
                                                /// Auto-generated field.
                                                /// To modify move field declaration from designer file to code-behind file.
                                                /// </remarks>
                                                protected global::System.Web.UI.WebControls.TextBox txtThaoTac;
}


