//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Views.QLKhieuNai.UserControls {
    
    
    public partial class BieuDoKNChoXuLy {
        
        /// <summary>
        /// UcTopContent1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Website.Views.QLKhieuNai.UserControls.UcTopContent UcTopContent1;
        
        /// <summary>
        /// chartSoLuongKhieuNaiTiepNhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.DataVisualization.Charting.Chart chartSoLuongKhieuNaiTiepNhan;
    }
}
