//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Views.QLKhieuNai.UserControls {
    
    
    public partial class KNBoPhanKhacChuyenVe {
        
        /// <summary>
        /// UcTopContent1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Website.Views.QLKhieuNai.UserControls.UcTopContent UcTopContent1;
        
        /// <summary>
        /// btnUpdateKNHangLoat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl btnUpdateKNHangLoat;
        
        /// <summary>
        /// btnDongKN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl btnDongKN;
        
        /// <summary>
        /// btnChuyenNgangHang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl btnChuyenNgangHang;
        
        /// <summary>
        /// btnChuyenPhanHoi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl btnChuyenPhanHoi;
        
        /// <summary>
        /// btnChuyenXuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl btnChuyenXuLy;
        
        /// <summary>
        /// btnTiepNhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl btnTiepNhan;
        
        /// <summary>
        /// UcFillter1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Website.Views.QLKhieuNai.UserControls.UcFillter UcFillter1;
        
        /// <summary>
        /// PopupChoXuLy1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Website.Views.QLKhieuNai.UserControls.PopupChoXuLy PopupChoXuLy1;
    }
}
